### ISSUE TITLE
Need Windows CI

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/fs-tree-diff#42]

**Comment by stefanpenner** [comment]
currently this does not touch anything platform specific (no actual disk stuff), but it can't hurt to add this.

**Comment by rwjblue** [comment]
@stefanpenner - As of https://github.com/stefanpenner/fs-tree-diff/pull/40 we will have a default implementation that touches disk, right?

**Comment by stefanpenner** [comment]
@rwjblue good point

**Comment by stefanpenner** [comment]
i'll do that now

**Comment by stefanpenner** [comment]
https://ci.appveyor.com/project/embercli/fs-tree-diff is up, but appveyor UI seems glitched out...
