### ISSUE TITLE
default delegate's `change` should no-op on systems that support symlinks

### ISSUE THREAD

**Issue by hjdivad** [stefanpenner/fs-tree-diff#46]
see discussion https://github.com/stefanpenner/fs-tree-diff/pull/40

**Comment by trentmwillis** [comment]
How should support be checked? I've looked at the [implementation in `symlinkOrCopy`](https://github.com/broccolijs/node-symlink-or-copy/blob/cd650ca94fbbbb9a9c5c4ac3fd458ec520d827e8/index.js#L13-L38) and could duplicate it, but that doesn't feel great.

**Comment by hjdivad** [comment]
@trentmwillis feels like  this should be an API of `symlinkOrCopy`; basically just have it expose either `options` or at least `options.canSymlink`.

thoughts?

**Comment by rwjblue** [comment]
@hjdivad - That is exactly what @trentmwillis did in https://github.com/broccolijs/node-symlink-or-copy/pull/30.

**Comment by rwjblue** [comment]
(and `symlink-or-copy` @ 1.1.8 is being used in https://github.com/stefanpenner/fs-tree-diff/pull/49 to address this issue)

**Comment by hjdivad** [comment]
@rwjblue cool, seems like we have a reasonable path forward here then.

That doesn't deal with @trentmwillis's "doesn't feel great" concern, but that seems like a problem for `symlinkOrCopy`, and in any case whatever `symlinkOrCopy` does to feature detect this is what we're already doing

**Comment by trentmwillis** [comment]
@hjdivad nope, I'm fine with this solution. The "doesn't feel great" comment stemmed primarily from duplicating the same support check logic.

**Comment by hjdivad** [comment]
@trentmwillis gotcha; I misread your initial comment then.

**Comment by hjdivad** [comment]
fixed by #49
