### ISSUE TITLE
Adding projections for symlink to make merge work

### ISSUE THREAD

**Issue by arthirm** [stefanpenner/fs-tree-diff#79]
## Problem

When merging 'n' trees where 'm' directories have same name and some of them are symlinked, except the last directory all the previous directories that are symlinked are missing. 

## Reason: 

Merge works by calling FSTree.readDirSync which basically returns the children of a given directory and it operates on entries. Since symlinked directories does not have its children's entries those directories are lost while merging.   

Why it was working prior to change tracking:
Earlier Merge was calling fs.readDirSync and since fs can walk through symlinks it was working fine.

## Proposed Solution:

Since we need to track the source directory when symlinking, projections can be created in current tree whenever we symlink. So a new API like this will be created 
`this.out.symlinkFromInput(this.in[0], 'source/relative/path', 'target/relative/path')`
This will be signature to call symlink from any plugin like funnel or merge-trees.

### Issue with the above signature:

The first parameter this.in[0] will work fine in broccoli-funnel and persistent-filter. But in merge there will be trees in in[0], in[1], etc.. So we wont know which tree to pass.
Solution:
Either we should have overloaded function from the above one that takes the first parameter as fsTree and one that takes fsMergeTree or ?

The proposed solution on using projections will require changes in the below API's as well. 

1. symlinkSyncFromInput - addProjections (projection is a map (key path, value fsTree ) or array of trees 
      E.g broccoli-merge-trees-input-base-path-jhgdf.tmp/0 can contain 2 directories. One can be vendor and other bower_components and both can be symlinked. So we need to store both in the current tree. Where key can be 'vendor' and value 'fsTree'

2. readFileSync - Should read file from projection if file not present in current tree. (should we read basePath from entry) 
3. readDirSync - read from projections 
4. writeFileSync ( analyze if basepath in fs.readFileSync should be changed (this.root or basePath from entry))
5. unlinkSync - clear  projection entry 
6. Entry (Should we also need base path?)
7. findbyRelativePath - read from projections if entries are not present (This will be used by all the above functions. That is the reason we might need basePath so that readFileSync for instance does not have to worry about reading from current tree or projected tree) 

[edit: headings]

**Comment by hjdivad** [comment]
> The first parameter this.in[0] will work fine in broccoli-funnel and persistent-filter. But in merge there will be trees in in[0], in[1], etc.. So we wont know which tree to pass.
Solution:
Either we should have overloaded function from the above one that takes the first parameter as fsTree and one that takes fsMergeTree or ?

Yes, `FSMergeTree` should be interchangeable with `FSTree` for these sorts of things. `symlinkFromInput` shouldn't need to know which kind of tree it got, and if it does, that suggests we need to add API to `FSMergeTree` and *not* add special branching logic within `symlinkFromInput`

----

Regarding "adding projections", I think the best way to start is simply for `symlinkFromInput` to store the projection on the entry.

```js
FSTree.prototype.symlinkSyncFromInput(srcFSTree, targetRelativePath, srcRelativePath) = function () {
  // other stuff
  let entry = new Entry( /* .... */, srcFSTree.chdir(srcRelativePath))
  entry._projection // <-- srcFSTree.chdir(srcRelativePath)
  // other stuff
}
```

Then things like `readdirSync` just check for this

```js
let entry = this.findByRelativePath(relativePath);
if (entry._projection) {
  return entry._projection.readdirSync('');
}
```

**Comment by hjdivad** [comment]
> unlinkSync - clear projection entry

Yes, although if there's no projection we'll want to do the current behaviour

**Comment by arthirm** [comment]
Agreed on storing on projections in entries, and i understand that symlinkFromInput shouldn't need to know which kind of tree it got. I can make sure it always receives FSTree. When symlink is called from merge logic in FSMergeTree we can make sure that we pass only FSTree. But when calling symlink from applyPatch of Broccoli-Merge-Trees, i dont understand how FSMergeTree will decide which FSTree to pass.

**Comment by arthirm** [comment]
Regarding unlinkSync - clear projection entry, yes this will be done in addition to current behavior.

**Comment by hjdivad** [comment]
> I can make sure it always receives FSTree. When symlink is called from merge logic in FSMergeTree we can make sure that we pass only FSTree.

What I was suggesting is we should pass `this.in` if that's appropriate (eg when applying patches) and add what we need to in `FSMergeTree` to make that work

**Comment by arthirm** [comment]
> What I was suggesting is we should pass this.in if that's appropriate (eg when applying patches) and add what we need to in FSMergeTree to make that work

So projections will basically contain FSTree or FSMergeTree depending on what is passed. And in FSTree.readDirSync and FSTree.readFileSync , to be able to write the below code i will create readDirSync and readFileSync in FSMergeTree as well. 

`if (entry._projection) {
  return entry._projection.readdirSync('relativePath');
}`

**Comment by stefanpenner** [comment]
This is great work, the resulting research lead to several improvements in the ecosystem. This issue is no longer active, and so it should likely be closed. It will remain as part of this project, and can be consulted if needed when in a closed state.

Thank you for the research!
