### ISSUE TITLE
Documentation: fix custom isEqual example

### ISSUE THREAD

**Issue by marcelobern** [stefanpenner/fs-tree-diff#85]
Under [section Change Calculation](https://github.com/stefanpenner/fs-tree-diff#change-calculation) the following code appears:
```javascript
var defaultIsEqual = FSTtreeDiff.isEqual;
```
when I believe the correct form would be:
```javascript
var defaultIsEqual = FSTree.defaultIsEqual;
```
Where it would be using `FSTree` to be consistent with the rest of the documentation and making reference to the actual exported function name `defaultIsEqual`.

**Comment by hjdivad** [comment]
thanks very much for catching this @marcelobern

**Comment by hjdivad** [comment]
see also #87 for testing at least compilation of the type declarations
