### ISSUE TITLE
TypeError: this is not a constructor

### ISSUE THREAD

**Issue by Turbo87** [stefanpenner/fs-tree-diff#90]
from https://github.com/ember-cli/ember-cli/pull/8481:

```
  TypeError: this is not a constructor
      at new FSTree.fromEntries (node_modules/fs-tree-diff/lib/index.js:76:16)
      at Context.<anonymous> (tests/unit/tasks/server/livereload-server-test.js:224:22)
```

it seems that the `return new this(...)` is not behaving as expected

/cc @stefanpenner

**Comment by stefanpenner** [comment]
‘new FSTree.fromEntries’ is not supported, fromEntries is a static method not a constructor. The bug is in ember-cli

**Comment by Turbo87** [comment]
oh, good catch, totally missed that strange invocation
